# Generated by Django 4.2 on 2023-05-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_meepform'),
    ]

    operations = [
    ]
