# Generated by Django 4.2 on 2023-05-13 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0006_meepform_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeepForm',
            new_name='MeepForm1',
        ),
    ]
