# Generated by Django 4.2.1 on 2023-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0008_meepform_delete_meepform1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
